name: Test BuildKite Plugins
description: Automatically run plugin tests (using bats)
author: https://github.com/buildkite-plugins
requirements:
  - bash
  - docker
configuration:
  properties:
    folders:
      oneOf:
        - type: string
        - type: array
          items:
            type: string
    pull:
      type: boolean
    version:
      type: string
  required: [ ]
  additionalProperties: false
