#!/bin/bash

set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/plugin.bash
. "$DIR/../lib/plugin.bash"


IMAGE_TAG=$(plugin_read_config VERSION 'v4.1.1')

DOCKER_CMD=(
  docker run --rm -ti
  -v "${PWD}":/plugin
)

if [ "$(plugin_read_config PULL 'false')" = 'true' ]; then
  DOCKER_CMD+=(--pull)
fi

# all docker options need to be above this line
DOCKER_CMD+=(buildkite/plugin-tester:"${IMAGE_TAG}")
# anything after this element will be the command executed in the container

if ! plugin_read_list_into_result FOLDERS; then
  # default value
  DOCKER_CMD+=(bats tests)
else
  DOCKER_CMD+=(bats "${result[@]}")
fi

"${DOCKER_CMD[@]}"
